#==========================================================================
# https://github.com/ophub/amlogic-s9xxx-armbian
# Description: Delete older releases and workflows runs
#==========================================================================

name: Delete older releases and workflows

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      delete_releases:
        description: "是否删除发布文件？"
        required: true
        default: true
        type: boolean
      delete_tags:
        description: "是否删除标签?"
        required: false
        default: true
        type: boolean
      prerelease_option:
        description: "是否区分预发布"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - true
          - false
      releases_keep_latest:
        description: "保留多少个最新版本"
        required: false
        default: "2"
        type: choice
        options:
          - 30
          - 20
          - 10
          - 9
          - 8
          - 7
          - 6
          - 5
          - 4
          - 3
          - 2
          - 1
          - 0
      releases_keep_keyword:
        description: "需要保留的关键字"
        required: false
        default: "v0/_save_/kernel_"
      delete_workflows:
        description: "是否删除工作流记录？"
        required: true
        default: true
        type: boolean
      workflows_keep_day:
        description: "保留工作流的天数"
        required: false
        default: "1"
        type: choice
        options:
          - 30
          - 20
          - 10
          - 9
          - 8
          - 7
          - 6
          - 5
          - 4
          - 3
          - 2
          - 1
          - 0
      workflows_keep_keyword:
        description: "保留工作流的关键字"
        required: false
        default: ""
      out_log:
        description: "输出详细的JSON日志"
        required: false
        default: true
        type: boolean

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: ${{ inputs.delete_releases }}
          delete_tags: ${{ inputs.delete_tags }}
          prerelease_option: ${{ inputs.prerelease_option }}
          releases_keep_latest: ${{ inputs.releases_keep_latest }}
          releases_keep_keyword: ${{ inputs.releases_keep_keyword }}
          delete_workflows: ${{ inputs.delete_workflows }}
          workflows_keep_day: ${{ inputs.workflows_keep_day }}
          workflows_keep_keyword: ${{ inputs.workflows_keep_keyword }}
          out_log: ${{ inputs.out_log }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
